### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by tomusborne** [justintadlock/customizer-typography#3]
More of a question than an issue.

Does combining controls like this offer any sort of performance boost in the Customizer, or is simply to better organize everything? Either way, thanks for the concept - really awesome.

**Comment by justintadlock** [comment]
I don't think so.  I was just testing out multiple settings tied to a single control at the time.  This seemed like a use case that would work for that.

**Comment by tomusborne** [comment]
Definitely cleans up the code. I figured reducing the amount of controls might offer faster speeds.

Thanks for the code, super useful.
